higan-emu/higan

libco/aarch64.c
Originally submitted as byuu/higan#77.
---
The current implementation accidentally saved and restored registers x8-x15 instead of d8-d15. I'm not aware of this causing any issues in bsnes/higan, but hey, might as well fix it.
Additionally, I used [this simple benchmark](https://github.com/Sintendo/libco/blob/aarch64/-test/test_timing.cpp) to see if it's possible to get this to run slightly faster. Here's some benchmark results from the ARM64 CPUs I happen to have access to:
| CPU | Before (s) | After (s) |
|:-------------|-------------:|-----:|
| AWS Gravitron | 26.4 | 18.1 |
| BCM2837 (RPi 3B) | 44.4 | 36.4 |
| BCM2711 (RPi 4B) | 35.4 | 28.1 |
Impact on emulation speed is very limited; I saw maybe a 1-2 FPS increase in bsnes using the most accurate settings on my RPi4.
=> libco/aarch64: Fix vector registers handling and optimizations

ruby/audio/alsa.cpp
The alsa driver opens the first device in the list of known devices which could be a device that cannot actually be opened. This changes the device to be opened to 'default'.
=> Let alsa driver open the default device if none set

higan/pce/cartridge/board/board.hpp, higan/target-byuu/emulator/emulator.hpp, nall/hid.hpp
A few classes with virtual methods were missing virtual destructors. Found with -Wdelete-non-virtual-dtor.
=> Fix missing virtual destructors

higan/target-byuu/byuu.cpp, icarus/icarus.cpp
Here we need to destroy instances of gui objects explicitly when exiting the main function.
=> Fix segfault on exit in byuu and icarus with qt5

.cirrus.yml, README.md
These commits remove `genius` from nightly build archives (it's still built, just not archived), add separate archives for higan and byuu, and update the README to link (directly) to all the builds for all platforms.
You can see a preview of the new README [in my fork](https://github.com/Screwtapello/higan/blob/16742edc7d9281c9c6fc062947bb061ee859e47c/README.md), although of course the byuu links won't work until this PR is merged and Cirrus has had a chance to actually build them.
Fixes #1.
=> CI updates

.cirrus.yml, extras/README.md, extras/byuu/settings.bml, extras/higan/paths.bml
byuu's config file is the one shipped with the official v4 binary for Windows, with the Windows-specific driver choices removed so the binary will use the platform defaults.
higan's config file should make it use the Templates directory shipped alongside it, instead of requiring it to be moved to a platform-specific location. It was originally Windows-only, but I'm not sure why since it's definitely useful on Linux too. Not sure if it works on macOS, but we can figure that out later.
Part of #2.
=> Include pre-made config files with nightly builds.

ruby/audio/pulseaudio.cpp
The elements of vector Audio::resamplers are accessed in method Audio::output if AudioDriver::dynamic is true. At that point however it is possible that the vector has zero elements because only a call to Audio::setChannels will fill the vector.
=> Fix pulseaudio segfault with dynamic rate setting

ruby/audio/pulseaudio-simple.cpp
Currently every other audio driver calls this method at initialization time, so for consistency alone we should call in here too.
=> Add .setChannels(2) to the PulseAudio-simple driver.

nall/recompiler/amd64/encoder-instructions.hpp
Every other block `#undef`ines "op" afterward, this one should too.
=> nall: Quiet a compiler warning about re-defining a macro.

icarus/compact-disc/compact-disc.cpp
After importing a BIN/CUE image, icarus stores it in a format which includes 2048 data bytes, 304 error correction bytes, and 96 subchannel data bytes per sector, for a total of 2448 bytes. Previously, icarus would allocate a 2048 byte buffer and try to read 2448 bytes of data into it, causing a buffer overflow and (sometimes) a crash. Now, we make sure tha buffer is correctly-sized before we fill it in.
Fixes #73.
=> icarus: Fix crash generating manifests for CDs.

higan-ui/panel-items/port-connector.cpp
Fix the trailing slash preventing to create a controller in higan-ui
=> Fix the trailing slash preventing to create a controller

higan/sfc/cpu/timing.cpp
This behaviour was introduced in v104r02 (1135716) to fix Nuke (PD), but it turns out there are a number of titles that depend on the initial state of the shift registers.
When the initial state is zero:
- Taikyoku Igo - Goliath: Pressing start or A takes you to the title screen, but pressing start or A at the title screen does nothing
When the initial state is non-zero:
- Nuke (PD): inputs do not work
- Tatakae Genshijin 2: attract sequence ends early
- Williams Arcade's Greatest Hits: inputs fire on their own
- World Masters Golf: inputs do not work at all
- Pro Football: Dropdown intro is interrupted and title screen is skipped
- Taikyoku Igo - Goliath: Pressing start or A takes you to the title screen, then immediately dismisses it
In v107r02 (2c84a4e) byuu changed the behaviour to …
=> sfc: Clear shift registers at start of auto joypad polling.

higan/sfc/ppu-performance/io.cpp
This fixes a graphical bug when booting Mahjong Taikai II for the SNES in the ppu-performance renderer.
The fix is copied from bsnes-emu. It checks the CPU vcounter rather than the PPU vcounter. The PPU vcounter only updates once per scanline in the performance renderer, so it is behind one scanline at this point.
=> fix SNES OAM address reset

byuu/settings/firmware.cpp, byuu/settings/paths.cpp
Fix "Assertion failed: source, file ../hiro/core/shared.hpp, line 895" using a debug build while trying to choose a firmware file or some other paths
=> byuu: Fix Assertion failed with some Path Selectors using a debug build

higan-ui/GNUmakefile
make install is missing $(higan.path) for the higan/System folder
=> higan-ui: fix make install for windows/macos

hiro/cocoa/widget/frame.cpp, hiro/cocoa/widget/frame.hpp
The way this widget retrieved its child sizable was faulty. In practice this meant that the various setX methods wouldn't propagate and while the Frame itself was visible, its contents usually weren't.
Luckily this widget is used sparingly, but most notably higan's audio/video/input settings panels were affected.
Before:
After:
=> hiro/cocoa: Fix Frame setVisible/setGeometry

higan-ui/emulator/platform.cpp
`/tmpfs/` doesn't exist on Linux, and the root directory of a system can only be modified by root, but `/tmp/` can be modified by anyone usually, so I changed this to Linux's standards, since more people use Linux than FreeBSD, but I can create a more nuanced solution to support both if you want.
=> Fix debug logging for Linux systems

higan/sfc/cpu/io.cpp, higan/sfc/cpu/timing.cpp
You cannot start a new game because input is not working on the title screen.
It's reading the auto joypad shift registers too early
(around v=225, h=49 dots), resulting in no input, since higan already
cleared the shift-registers of the previous frame.
Auto-joypad-read should start on v=225 between h=32.5 and h=95.5
according to Anomie's timing doc. Hardware-testing has shown that the
range should be h=32.5 to h=96 or you'd miss it on a few frames.
In the current code auto-joypad-read can start anywhere on the scanline.
Ys 5 had a similar problem back in bsnes v085 and is still working.
It turned auto-joypad-read on late in vblank and that was breaking input.
Also emulated that Auto-Joypad-Read is disabled while it is running,
when you disable it for the rest of the frame in the 4200 …
=> SFC: Fix auto-joypad-read in Taikyoku Igo - Goliath

hiro/gtk/desktop.cpp, hiro/gtk/window.cpp, hiro/qt/desktop.cpp, nall/xorg/clipboard.hpp, ruby/video/video.cpp, ruby/video/xvideo.cpp
Previously, hiro and ruby set `only_if_exists=True` when querying the X server for atoms. Thus, when running with a window-manager that has already set up `_NET_WORKAREA` and `EDID` atoms, higan retrieved them and used them to query for properties. When running *outside* a window-manager, higan would not create those atoms, and thus wound up sending invalid queries and crashing.
Now, we always set `only_if_exists=False`, and thus always create the atoms we want to use. It's just one less failure mode to worry about.
Fixes #11.
=> In X11, don't require a running window manager.

higan/gb/ppu/io.cpp, icarus/cartridge/game-boy.cpp
1. OBP0 was read incorrectly, resulting in incorrect sprite colors.
2. The 'icarus' tool did not support 128KB and 64KB SRAM sizes.
3. The MBC3 mapper did not recognize >32KB SRAM, breaking save games.
There is still a bug with the realtime clock that I was unable to fix.
See https://github.com/higan-emu/higan/issues/85#issuecomment-678931345 for more details.
=> Fix palettes and save games in Pokemon Crystal (issue #85)

higan/gb/ppu/cgb.cpp
This fixes a bug setting the background priority bits in cgb.cpp. Fixes issue #96 and #97
References:
https://github.com/higan-emu/higan/blob/master/higan/gb/ppu/cgb.cpp#L110
https://github.com/higan-emu/higan/blob/master/higan/gb/ppu/cgb.cpp#L135
This type used to be "bool" in earlier higan releases but was changed to uint1.
Assigning "attr & 0x80" will set priority to true (1) when bit 7 is set.
But with the uint1 type, it ends up always setting the value to false (0)
I changed it to nall::boolean, which acts the same way and carries the "default initialize to 0" behavior of uint1.
bool would default to not being initialized and since I can't rule out side effects for that change, I went with the boolean type.
=> Update GBC ppu.hpp to fix background priority bugs

byuu/emulator/famicom.cpp, byuu/emulator/game-boy-advance.cpp, byuu/emulator/game-boy.cpp, byuu/emulator/mega-drive.cpp, byuu/emulator/nintendo-64.cpp, byuu/emulator/pc-engine.cpp, byuu/emulator/playstation.cpp, byuu/emulator/super-famicom.cpp, byuu/emulator/wonderswan.cpp, byuu/input/input.cpp, byuu/input/input.hpp, byuu/settings/input.cpp
-Adds missing Left and Right Trigger mappings
-Adds missing Left and Right Stick mappings
-Removes N64 labels from "Virtual Pad"
-Rebinds N64 C Buttons to Right Thumbstick
-Rebinds N64 Z Trigger from "select button" to "left trigger"
-Renamed default virtual pad mappings to Microsoft labels (no I don't own this pad, but it's definitely the most popular of the 3, and that's why I think it should be default)
I agree with Asura that the Nintendo and Sony mappings should also appear as a dropdown changer or via two additional columns. Someone else can do that as it's beyond my skill. Even if that doesn't get in with this PR, this is still an improvement as it explicitly states "Microsoft layout" in the column header, thus preventing users from assuming it's Nintendo layout and confusing …
=> Expansion and renaming of virtual pad inputs

ruby/input/joypad/xinput.cpp
It dawned on me that with a very minor change we could fix this correctly, and in all three GUIs at once!
The problem is that the axis and trigger handling are the same in the emulators. 0 is considered neutral (not pressed), -32768 is considered pressed in one direction, and +32767 is considered pressed in the other direction. That works great for a stick that can move both ways. But a trigger only moves in one way. So if we use the range 0 to +32767, then assigning the trigger will always do the right thing and choose Trigger.Hi, and 0 will be seen as neutral or not pressed. Whereas before, using the range -32768 to +32767, it would sense Trigger.Lo since you started changing the input value while it was negative.
=> Fix XInput trigger button ranges (fixes #108)

higan/ps1/cpu/core/memory.cpp, higan/ps1/cpu/cpu.cpp, higan/ps1/cpu/cpu.hpp, higan/ps1/cpu/debugger.cpp, higan/ps1/memory/bus.hpp
One obvious improvement is that this solves the 'black road' issue in Ridge Racer (note that the broken polygons are part of an unrelated problem)
As this is such a fundamental flaw, chances are there are significant improvements to other games too.
before:
after:
=> ps1: cache isolate bit should isolate i-cache, not d-cache (scratchpad)

.github/workflows/build.yml
This pull request implements a continuous build process for building Higan.
- Implements native builds for Ubuntu, Windows and macOS.
- Builds Higan piece-wise by running a matrix over the programs (higan-ui, byuu, icarus) and the OS (for a total of 9 jobs.)
- Produces a "nightly" build release that is continuously updated with the latest binaries. This gives a consistent URL to get the latest nightly build. See, for example, on my fork: https://github.com/jchw-forks/higan/releases/tag/nightly
- Produces a version release on each tag starting with v. For example, see https://github.com/jchw-forks/higan/releases/tag/v116. (We could make this a draft so release notes can be edited and a release could be manually published, too, but right now it just publishes the release immediately.)
The …
=> Implement GitHub Actions based CI.

.github/workflows/build.yml
This is a bit trickier than expected, but it basically encapsulates the desired logic; it checks to see if we're on a ref that we would want to release for. There seems to be no good way to detect PRs; the previous code was a sham I copy-pasted without validating.
See it in action here:
- Running on master: https://github.com/jchw-forks/higan/actions/runs/300278278
- Running on a PR: https://github.com/jchw-forks/higan/actions/runs/300281344
=> Prevent GitHub Actions from releasing on PRs.

higan-ui/GNUmakefile
Fix an issue where the Higan template directory was created as `~/Library/Application Supporthigan-ui/` rather than `~/Library/Application Support/higan-ui/` due to a typo in the install makefile target.
The second commit in this PR fixes an issue where templates were copied to `~/Library/Application Support/higan-ui/System/`  where the higan-ui application was searching for templates in `~/Library/Application Support/higan-ui/`
With this PR, higan-ui works as expected after running `make install` on a macOS target.
=> higan: fix invalid "Application Support" path on macOS

higan-ui/program/program.cpp
Fixes an issue where higan-ui would not exit when 'Quit' is selected in the Mac menu bar.
byuu/icarus were already working as expected, so didn't need a patch.
=> mac: Quit higan when 'Quit' is selected in the main menu bar

.cirrus.yml
Apparently Ports only supports the latest stable release, not earlier releases in the 12.x family.
=> Update the FreeBSD image to fix a build failure.

higan/md/mcd/io.cpp
WRAM should only be switched back when writing a 1-bit to $ff8003.d0 (RET bit) for the Mega CD.
This fix allows Popful Mail to boot and be mostly playable.
=> [Mega CD] fix sub-CPU WRAM switching behavior [TascoDLX]

higan/md/mcd/io.cpp
This change fixes a bad bit-range on $ff8004 writes, which fixes the game Radical Rex.
Before it would hang at the title screen, and now the game is playable.
=> [Mega CD] fix bitrange for CDC transfer destination writes [TascoDLX]

higan/component/processor/z80/instruction.cpp, higan/component/processor/z80/z80.cpp, higan/md/apu/apu.cpp, higan/md/apu/apu.hpp, higan/md/apu/serialization.cpp, higan/md/cpu/bus.cpp, higan/md/cpu/io.cpp, higan/md/system/system.cpp, higan/md/vdp/vdp.cpp
1) MD reset logic -- fixes various issues that arise when switching games
2) Z80 interrupt processing -- corrects music tempo in Air Buster & US SegaCD v2 BIOS
3) Z80 IRQ duration - avoids timing issues and unnecessary interrupt processing in some games
4) 68K->Z80 bus control - fixes Fatal Rewind boot & music in US SegaCD v1 BIOS
5) Z80 timing fixes - based on info published in "The Undocumented Z80 Documented" by Sean Young
=> MegaDrive+Z80 fixes

higan/md/mcd/gpu.cpp, higan/md/mcd/io.cpp, higan/md/mcd/mcd.hpp, higan/md/mcd/serialization.cpp, higan/md/mcd/timer.cpp
1) gfx rate - period based on cpu clock, not master clock (fixes slow graphics update)
2) timer - revised to periodic timer (fixes #139)
=> Mega-CD quick fixes

higan-ui/GNUmakefile
Apparently -march=native doesn't behave the same way on ARM as it does on x86, and clang doesn't support it at all, so when building with local=true we need to detect the architecture.
=> higan-ui: Don't use -march=native on ARM systems.

higan/sfc/cpu/cpu.hpp, higan/sfc/cpu/io.cpp, higan/sfc/cpu/serialization.cpp, higan/sfc/cpu/timing.cpp
In commit e422ddc, Jonas Quinn updated higan's implementation of the auto-joypad-poll mode. Those fixes were ported to bsnes in commit 39c37ec, but a problem was found with the game "SpellCraft - Aspects of Valor", fixed in bsnes in commit 4f7a269. That fix was back-ported to higan in commit 44cbb88, but that change caused a regression in "Secret of Mana" (issue #170).
This commit (helpfully provided by Jonas Quinn once again) re-ports the bsnes changes back to higan, and the problems should be solved once and for all.
Fixes #170.
=> sfc: Really fix automatic joypad polling, for sure.

higan/md/vdp/io.cpp
This fixes graphical corruption when starting Golden Axe II. All credit to Eke for this fix.
=> [MD] Fix control port writes to always set command/address bits

nall/primitives/bit-range.hpp
Natural/Integer<T>.bit() (BitRange) was shifting by whatever type the source was to match the target bit length.
But this breaks when the target type is u64/s64 and the source type is u32/s32 or smaller. Shifting by >=32 becomes undefined behavior.
We have to cast the input source to the target type first, so that the source<<shift result is valid.
This is safe here regardless of source's signedness, because it's only used in =, &=, ^=, |= operations.
=> Fix critical undefined bit-shift length operation

higan/gba/cpu/bus.cpp, higan/gba/cpu/cpu.hpp, higan/gba/cpu/io.cpp, higan/gba/cpu/memory.cpp, higan/gba/cpu/serialization.cpp, higan/gba/system/bios.cpp
The reason that IWRAM and EWRAM appear to be disabled is because they were swapped with the BIOS.
(Thanks to kevtris for disclosure of this behaviour.)
=> gba: memory.disable is actually memory.biosSwap

higan/component/processor/m68k/algorithms.cpp
The source and target values need to be clipped to their instruction size.
For instance, CMP.W should only compare the low 16-bits of the input values, not the entire 32-bits.
This will fix severe graphics corruption in the game Alien Soldier for the Mega Drive, and likely more games as well.
=> Fix clipping bug in M68000 ADD/CMP/SUB instructions

higan/component/processor/sm83/instructions.cpp
In the original gameboy's instruction file, the old DAA instruction modified the A register and used the modified value for further checks.
Also, the carry flag was not set properly.
=> Fix DAA instruction

hiro/gtk/application.cpp
when running with Wayland higan crashes with the following error because GDK backend was not properly set:
```
(higan:2515): Gdk-CRITICAL **: 08:23:32.132: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed
X Error of failed request:  BadWindow (invalid Window parameter)
```
The same fix in ares repository: https://github.com/ares-emulator/ares/pull/9/commits/805d4bd3b1ba7bfa620813f7331f6993aa1d2383
Tested on Ubuntu 22.04&23.04, Fedora 37&38.
=> hiro: Force Gtk3 to use X11 backend

.github/workflows/build.yml, nall/windows/guard.hpp
Copied from commit ea05fa0c3e8256f387c810311ebbaaffe5c3b528 in the bsnes repository.
=> CI: Update the 'nightly' tag along with the release.
